Controllers/BookViewController.cs
using LibraryApp.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;

namespace LibraryApp.Controllers
{
    public class BookViewController : Controller
    {
        private readonly IBookRepository _bookRepository;

        public BookViewController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        [HttpGet("/book/edit/{id}")]
        public IActionResult EditBook(Guid id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View("~/Views/Home/EditBook.cshtml", book);
        }

        [HttpGet("/book/add")]
        public IActionResult AddBook()
        {
            return View("~/Views/Home/AddBook.cshtml");
        }

        [HttpGet("/books")]
        public IActionResult DisplayBooks()
        {
            var books = _bookRepository.GetAllBooks();
            return View("~/Views/Home/DisplayBooks.cshtml", books);
        }

        [HttpGet("/books/search")]
        public IActionResult GetBooks([FromQuery] string title = null, [FromQuery] string author = null, [FromQuery] string genre = null)
        {
            var books = _bookRepository.GetAllBooks();

            var booksFiltered = books.AsQueryable();

            if (!string.IsNullOrEmpty(title))
            {
                booksFiltered = booksFiltered.Where(book => book.Title.ToLower() == title.ToLower());
            }
            if (!string.IsNullOrEmpty(author))
            {
                booksFiltered = booksFiltered.Where(book => book.Author.ToLower() == author.ToLower());
            }
            if (!string.IsNullOrEmpty(genre))
            {
                booksFiltered = booksFiltered.Where(book => book.Genre.ToLower() == genre.ToLower());
            }
            return View("~/Views/Home/DisplayBooks.cshtml",booksFiltered.ToList());
        }

        [HttpGet("/book/{id}")]
        public IActionResult BookDetails(Guid id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }

            return View("~/Views/Home/BookDetails.cshtml", book);
        }

        [HttpGet("/chart")]
        public IActionResult BorrowingChart()
        {
            return View("~/Views/Home/BorrowingChart.cshtml");
        }
    }
}

Controllers/BorrowTransactionViewController.cs
using LibraryApp.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using LibraryApp.Models.ViewModels;

namespace LibraryApp.Controllers
{
    public class BorrowTransactionViewController : Controller
    {
        private readonly IBorrowTransactionRepository _borrowTransactionRepository;
        private readonly IBookRepository _bookRepository;
        public BorrowTransactionViewController(IBorrowTransactionRepository borrowTransactionRepository, IBookRepository bookRepository)
        {
            _borrowTransactionRepository = borrowTransactionRepository;
            _bookRepository = bookRepository;
        }

        [HttpGet("/borrowings")]
        public IActionResult DisplayBorrowingList()
        {
            var borrows = _borrowTransactionRepository.GetBorrowTransactions();
            var borrowingList = new List<BorrowingListViewModel>();

            foreach (var borrow in borrows)
            {
                var book = _bookRepository.GetBookById(borrow.BorrowedBook); 
                if(book == null)
                {
                    break;
                }
                borrowingList.Add(new BorrowingListViewModel
                {
                    Id = borrow.Id,
                    Surname = borrow.Surname,
                    BorrowDate = borrow.BorrowDate,
                    DueDate = borrow.DueDate,
                    ReturnDate = borrow.ReturnDate,
                    Status = borrow.Status,
                    BookTitle = book.Title 
                });
            }

            return View("~/Views/Home/DisplayBorrowingList.cshtml", borrowingList);
        }

        [HttpGet("/borrow")]
        public IActionResult AddTransaction()
        {
            var id = HttpContext.Request.Query["id"].ToString();
            ViewBag.Id = id;
            var title = HttpContext.Request.Query["title"].ToString();
            ViewBag.Title = title;
            return View("~/Views/Home/BorrowBook.cshtml");
        }

        [HttpGet("/borrowings/borrowdate/search")]
        public IActionResult GetBorrowedTransactionsOverTimeByBorrowDate([FromQuery] string startDate = null, [FromQuery] string endDate = null)
        {
            var borrowingList = new List<BorrowingListViewModel>();

            if (string.IsNullOrEmpty(startDate) || string.IsNullOrEmpty(endDate))
            {
                ViewBag.ErrorMessage = "Both startDate and endDate must be provided.";
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }

            if (!DateTime.TryParse(startDate, out DateTime startDateFormat))
            {
                ViewBag.ErrorMessage = $"Invalid start date format: {startDate}. Expected format is yyyy-MM-dd.";
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }

            if (!DateTime.TryParse(endDate, out DateTime endDateFormat))
            {
                ViewBag.ErrorMessage = $"Invalid end date format: {endDate}. Expected format is yyyy-MM-dd.";
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }

            try
            {
                var borrows = _borrowTransactionRepository.GetBorrowedTransactionsOverTimeByBorrowedDate(startDateFormat, endDateFormat);
                foreach (var borrow in borrows)
                {
                    var book = _bookRepository.GetBookById(borrow.BorrowedBook);
                    borrowingList.Add(new BorrowingListViewModel
                    {
                        Id = borrow.Id,
                        Surname = borrow.Surname,
                        BorrowDate = borrow.BorrowDate,
                        DueDate = borrow.DueDate,
                        ReturnDate = borrow.ReturnDate,
                        Status = borrow.Status,
                        BookTitle = book.Title
                    });
                }
                return View("~/Views/Home/DisplayBorrowingList.cshtml", borrowingList);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }
        }
        [HttpGet("/borrowings/duedate/search")]
        public IActionResult GetBorrowedTransactionOverTimeByDueDate([FromQuery] string startDate = null, [FromQuery] string endDate = null)
        {
            var borrowingList = new List<BorrowingListViewModel>();

            if (string.IsNullOrEmpty(startDate) || string.IsNullOrEmpty(endDate))
            {
                ViewBag.ErrorMessage = "Both startDate and endDate must be provided.";
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }

            if (!DateTime.TryParse(startDate, out DateTime startDateFormat))
            {
                ViewBag.ErrorMessage = $"Invalid start date format: {startDate}. Expected format is yyyy-MM-dd.";
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }

            if (!DateTime.TryParse(endDate, out DateTime endDateFormat))
            {
                ViewBag.ErrorMessage = $"Invalid end date format: {endDate}. Expected format is yyyy-MM-dd.";
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }

            try
            {
                var borrows = _borrowTransactionRepository.GetBorrowedTransactionsOverTimeByDueDate(startDateFormat, endDateFormat);
                foreach (var borrow in borrows)
                {
                    var book = _bookRepository.GetBookById(borrow.BorrowedBook);
                    borrowingList.Add(new BorrowingListViewModel
                    {
                        Id = borrow.Id,
                        Surname = borrow.Surname,
                        BorrowDate = borrow.BorrowDate,
                        DueDate = borrow.DueDate,
                        ReturnDate = borrow.ReturnDate,
                        Status = borrow.Status,
                        BookTitle = book.Title
                    });
                }
                return View("~/Views/Home/DisplayBorrowingList.cshtml", borrowingList);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("~/Views/Home/DisplayBorrowingList.cshtml");
            }
            
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
  <link rel="stylesheet" href="~/lib/assets/css/now-ui-dashboard.css">
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="orange">
      <div class="logo">
        <a href="#" class="simple-text logo-mini">
          <i class="now-ui-icons education_agenda-bookmark"></i>
        </a>
        <a href="#" class="simple-text logo-normal">
          Library App
        </a>
      </div>
      <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
          <li class="" id="add-book">
            <a asp-controller="BookView" asp-action="AddBook">
              <i class="now-ui-icons ui-1_simple-add"></i>
              <p>Add Book</p>
            </a>
          </li>
          <li class="" id="borrowing-chart">
            <a asp-controller="BookView" asp-action="BorrowingChart">
              <i class="now-ui-icons business_chart-bar-32"></i>
              <p>Book Chart</p>
            </a>
          </li>
          <li class="" id="display-books">
            <a asp-controller="BookView" asp-action="DisplayBooks">
              <i class="now-ui-icons design_bullet-list-67"></i>
              <p>Display Books</p>
            </a>
          </li>
          <li class="" id="display-borrowing-list">
            <a asp-controller="BorrowTransactionView" asp-action="DisplayBorrowingList">
              <i class="now-ui-icons design_bullet-list-67"></i>
              <p>Display Borrowings</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div id="main-panel" class="main-panel ps">
            <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute"></nav>
            <div class="panel-header panel-header-sm"></div>
            <div class="content">
                <div class="card">
                    <div class="card-header"></div>
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
    </div>
  </div>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="~/lib/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="~/lib/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="~/lib/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="~/lib/assets/js/plugins/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
  <script src="~/lib/assets/js/now-ui-dashboard.js" type="text/javascript"></script>
  @await RenderSectionAsync("Scripts", required: false)
<script>
    function activate(element) {
        const ulElement = document.querySelector('.sidebar-wrapper').firstChild;
        const liElements = ulElement.children;

        liElements.forEach(li => {
            li.classList.remove("active");
        })

        element.classList.add("active");
    }
</script>
</body>
</html>